CREATE TABLE EMPLOYEES
(
  EMPLOYEE_SSN          VARCHAR(11)   NOT NULL,
  EMPLOYEE_FIRST_NAME   VARCHAR(15)   NOT NULL,
  EMPLOYEE_MIDDLE_NAME  VARCHAR(15),
  EMPLOYEE_LAST_NAME    VARCHAR(15)   NOT NULL,
  EMPLOYEE_POSITION     VARCHAR(15)   NOT NULL,
  EMPLOYEE_PHONE        CHAR(10)      NOT NULL,
  EMPLOYEE_STREET       VARCHAR(30)   NOT NULL,
  EMPLOYEE_CITY         VARCHAR(15)   NOT NULL,
  EMPLOYEE_ZIP          INTEGER(5)    NOT NULL,
  EMPLOYEE_STATE        CHAR(2)       NOT NULL,
  EMPLOYEE_SALARY       DECIMAL(8,2)  NOT NULL,
  EMPLOYEE_HOURLY_RATE  DECIMAL(4,2)  NOT NULL,
  EMPLOYEE_START_DATE   DATE,
  CONSTRAINT EMPLOY_PK  PRIMARY KEY (EMPLOYEE_SSN)
);

CREATE TABLE CUSTOMERS
(
  CUST_ID       VARCHAR(10)   NOT NULL primary key,
  CUST_NAME     VARCHAR(30)   NOT NULL,
  CUST_STREET   VARCHAR(30)   NOT NULL,
  CUST_CITY     VARCHAR(15)   NOT NULL,
  CUST_STATE    CHAR(2)       NOT NULL,
  CUST_ZIP      INTEGER(5)    NOT NULL,
  CUST_PHONE    CHAR(10)      NOT NULL
);

CREATE TABLE ORDERS
(
  PRODUCT_ID    VARCHAR(10)   NOT NULL primary key,
  CUST_ID       VARCHAR(10)   NOT NULL,
  DATE_ORDERED  DATE          NOT NULL,
  PRODUCT_NAME  VARCHAR(30)   NOT NULL,
  CONSTRAINT CUST_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS (CUST_ID)
);
